### PR TITLE
Downloading files as attachments

### PR DESCRIPTION
**Pull request by seansaleh**
To fix bug #12

### CODE REVIEW

**Comment by seansaleh** [comment]
Rereading the bug this won't fix it
Rather this will fix a separate issue: on mobile browsers (or at least mobile chrome on Android) .epub gets downloaded as .zip

**Comment by gerow** [comment]
Will this still allow, for example, playing audio in the browser without forcing it to be downloaded first? I'm just not certain what the semantics are with an "attachment".

**Comment by seansaleh** [comment]
Hmmmm, this is true, I did not think of that use case. This would either
require more special casing based on the file type or giving up :/
(It would mean a .mp3 or .txt would always download)

**Comment by seansaleh** [comment]
Abandoning

**Pull request closed without merging**
